[package]
name = "quilting-game"
version = "0.1.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]

[dependencies]
rand = "^0.3.15"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
clippy = { version = "0", optional = true }
